### ISSUE TITLE
Define how the hackathon should make use of worksheets

### ISSUE THREAD

**Issue by lr292358** [codalab/codalab#1013] opened 2015-05-06 17:56 UTC
We need to know what is the best way to conduct the hackathon.

The current idea is:

- People install worksheets on their laptops, for Windows users, we prepare an ubuntu image for Virtual Box with worksheets already installed. We give them a tutorial on worksheets and all needed instructions.

- We set up worksheet servers, one server per user, each server is then used by only one person (no waiting). Time limit is to allow equal compute power. The other way might be to use one central server and queuing system, but this might be too complicated (needs discussion).

**Comment by Raisins** [comment] 2015-05-07 16:20
July 31st

**Comment by lr292358** [comment] 2015-05-13 15:42
This will happen at Stanford, not Petersburg

**Comment by ErickWa** [comment] 2015-08-18 18:04
Closed as duplicate of #1077

**Closed by ErickWa** 2015-08-18 18:04 UTC
Labels: Worksheet
