### ISSUE TITLE
Making participant submissions public

### ISSUE THREAD

**Issue by ErickWa** [codalab/codalab#892] opened 2015-02-25 17:36 UTC
Feature 1.) Add a button that allows competition submitter to make their submissions available from the Leaderboard, (publicly) from panel: http://codalabtest.cloudapp.net/competitions/xxx#participate-submit_results (Where XXX is the competition number)

![image](https://cloud.githubusercontent.com/assets/4361560/6376251/a28c4634-bcd1-11e4-89e8-f4daebab582a.png)
 
Add the button to the right-hand side of this screen.

Feature 2.) Once they make their submission public, give them a "Thank you" notification.

**Comment by ckcollab** [comment] 2015-04-01 16:11
Duplicate of issue #893

**Closed** 2015-04-01 16:11 UTC
Labels: Competition, P1
