### ISSUE TITLE
Worksheet bundle transfer to competition side

### ISSUE THREAD

**Issue by madclam** [codalab/codalab#801] opened 2014-12-17 07:04 UTC
We need a mechanism to be able to submit bundles that are the result of calculations on the worksheet side as competition entries, without having to download them from the worksheet side and re-upload them to the competition side.

It would be also good to be able to submit entire worksheets.

**Comment by ErickWa** [comment] 2015-08-18 18:10
Duplicate of existing Worksheet issues, such as #994

**Closed by ErickWa** 2015-08-18 18:10 UTC
Labels: Competition, Worksheet
